routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',['as' => 'admin.index', function () {
    return view('welcome');
}]);

Route::group(['prefix' => 'admin', 'middleware' =>  'auth'], function(){

    Route::get('/',['as' => 'admin.index', function () {
    return view('welcome');
    }]);

	Route::resource('users', 'UsersController');
	Route::get('users/{id}/destroy', [
        'uses' => 'UsersController@destroy',
        'as'   => 'admin.users.destroy'

	]);

    Route::resource('categories', 'CategoriesController');
    Route::get('categories/{id}/destroy', [
        'uses' => 'CategoriesController@destroy',
        'as'   => 'admin.categories.destroy'
    ]);

    Route::resource('tags', 'TagsController');
    Route::get('tags/{id}/destroy', [
        'uses' => 'TagsController@destroy',
        'as'   => 'admin.tags.destroy'
    ]);

    Route::resource('articles', 'ArticlesController');
    Route::get('articles/{id}/destroy', [
        'uses' => 'ArticlesController@destroy',
        'as'   => 'admin.articles.destroy'
    ]);

    Route::get('images', [
         'uses' => 'ImagesController@index',
         'as'   => 'admin.images.index'
        ]);


});

Route::get('admin/auth/login', [
	'uses'   => 'Auth\AuthController@getLogin',
	'as'     => 'admin.auth.login'
]);

Route::post('admin/auth/login', [
	'uses'   => 'Auth\AuthController@postLogin',
	'as'     => 'admin.auth.login'
]);

Route::get('admin/auth/logout', [
	'uses'   => 'Auth\AuthController@getLogout',
	'as'     => 'admin.auth.logout'
]);

resources/views/admin/template/partials/errors.blade.php
@if(count($errors) > 0)
         <div class="alert alert-danger" role="alert">
             <ul>
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
             </ul>            
         </div>   
    @endif

resources/views/admin/template/partials/nav.blade.php
<nav class="navbar navbar-default">
  <div class="container-fluid">
   
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    @if(Auth::user())
      <ul class="nav navbar-nav">
        <li><img width="40px" height="40px" class="admin-logo-nav" src="{{ asset('image/laravel.png')}}"></li>
        <li><a href="{{ route('admin.index') }}">Inicio</a></li>
        <li><a href="{{ route('admin.users.index') }}">Usuarios</a></li>
        <li><a href="{{ route('admin.categories.index') }}">Categorias</a></li>
        <li><a href="{{ route('admin.articles.index') }}">Articulos</a></li>
        <li><a href="{{ route('admin.images.index') }}">Imagenes</a></li>
        <li><a href="{{ route('admin.tags.index') }}">Tags</a></li>        
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Pagina principal</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ Auth::user()->name }} <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{{ route('admin.auth.logout') }}">Salir</a></li>           
          </ul>
        </li>
      </ul>
      @endif
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>